
import React from "react";
import { Helmet } from "react-helmet-async";
import { Link } from "react-router-dom";
import { ArrowLeft, AlertTriangle } from "lucide-react";
import { Button } from "@/components/ui/button";
import { Separator } from "@/components/ui/separator";

export default function Disclaimer() {
  return (
    <>
      <Helmet>
        <title>Disclaimer | Zyfoox - Important Information for Users</title>
        <meta name="description" content="Read Zyfoox's Disclaimer: Learn about the limitations, responsibilities, and important information regarding our AI tools, content downloaders, and digital services." />
        <meta name="keywords" content="disclaimer, legal notice, content usage, AI tools disclaimer, downloader disclaimer, user responsibility" />
        <link rel="canonical" href="https://zyfoox.com/disclaimer" />
      </Helmet>

      <div className="container mx-auto px-4 py-16 max-w-4xl">
        <Button variant="ghost" size="sm" asChild className="mb-6">
          <Link to="/">
            <ArrowLeft className="h-4 w-4 mr-2" />
            Back to Home
          </Link>
        </Button>

        <div className="mb-12 text-center">
          <div className="inline-block bg-yellow-500/10 p-3 rounded-full mb-4">
            <AlertTriangle className="h-8 w-8 text-yellow-500" />
          </div>
          <h1 className="text-4xl font-bold mb-4">Disclaimer</h1>
          <p className="text-muted-foreground">Last Updated: {new Date().toLocaleDateString('en-US', { year: 'numeric', month: 'long', day: 'numeric' })}</p>
        </div>

        <div className="glass-card rounded-xl p-8 mb-12 prose prose-lg dark:prose-invert max-w-none">
          <p className="lead text-lg font-medium">
            Please read this disclaimer carefully before using Zyfoox's services and tools. This disclaimer outlines important information regarding the limitations, responsibilities, and legal considerations associated with our platform.
          </p>
          
          <h2 className="text-2xl font-semibold mt-8 mb-4">General Information</h2>
          <p>
            Zyfoox provides AI-powered tools and content downloaders designed to assist users with various digital tasks. The information, tools, and services provided on our platform are for general informational and convenience purposes only. While we strive to offer accurate, useful, and up-to-date tools and services, we make no representations or warranties of any kind, express or implied, regarding the accuracy, adequacy, validity, reliability, availability, or completeness of any information or results generated by our tools.
          </p>
          <p>
            By using Zyfoox, you acknowledge and agree that your use of our platform and reliance on any information or outputs generated by our tools is solely at your own risk. We strongly recommend that users exercise discretion and critical judgment when utilizing the content, suggestions, and outputs produced by our AI tools, as these are algorithmic interpretations and may not always align with specific individual needs or contexts.
          </p>

          <h2 className="text-2xl font-semibold mt-8 mb-4">Content Downloaders and Intellectual Property</h2>
          <p>
            Zyfoox offers tools that facilitate the downloading of content from various social media platforms and websites. It is important to understand that our downloaders are technical tools designed to help users access and save content for personal, non-commercial use only. We emphasize that users must:
          </p>

          <div className="my-8 p-6 bg-yellow-500/5 border border-yellow-500/20 rounded-lg">
            <h3 className="text-xl font-medium mb-4">User Responsibilities for Downloaded Content</h3>
            <ul className="list-disc pl-6 space-y-2">
              <li>Respect copyright laws and intellectual property rights when downloading and using content</li>
              <li>Obtain proper authorization from content creators or rights holders before downloading and using their content</li>
              <li>Adhere to the terms of service of the original platforms from which content is being downloaded</li>
              <li>Only download content for personal use, educational purposes, or other legally permitted uses under applicable fair use doctrines</li>
              <li>Not use downloaded content for commercial purposes without appropriate licenses or permissions</li>
              <li>Not redistribute, publish, or share downloaded content in ways that violate copyright laws or creator rights</li>
            </ul>
          </div>

          <p>
            Zyfoox does not host, store, or distribute any third-party content. Our tools merely facilitate the user's technical ability to download content that is already publicly accessible. We do not encourage, endorse, or promote copyright infringement or any unlawful use of downloaded materials. As a platform, we respect intellectual property rights and expect our users to do the same.
          </p>
          
          <p>
            If you are a content creator or copyright holder and believe that our tools are being used to infringe upon your rights, please contact us immediately through our <Link to="/contact" className="text-primary hover:underline">contact page</Link> or review our <Link to="/dmca" className="text-primary hover:underline">DMCA policy</Link> for information on how to submit a takedown notice.
          </p>

          <h2 className="text-2xl font-semibold mt-8 mb-4">AI-Generated Content Limitations</h2>
          <p>
            The AI tools provided by Zyfoox generate content based on mathematical models and algorithms trained on general data. While these tools are designed to produce helpful and relevant outputs, users should be aware of the following limitations:
          </p>
          
          <ul className="list-disc pl-6 space-y-2 mt-4">
            <li>AI-generated content may contain inaccuracies, inconsistencies, or factual errors</li>
            <li>Our tools may occasionally produce outputs that reflect biases present in training data</li>
            <li>AI-generated suggestions for business names, ideas, branding, or marketing content should be thoroughly reviewed and validated before implementation</li>
            <li>The quality and relevance of outputs depend significantly on the clarity and specificity of user inputs</li>
            <li>AI tools cannot replace professional advice in specialized fields such as law, finance, health, or other regulated industries</li>
          </ul>
          
          <p>
            We recommend that users view our AI-generated outputs as starting points or creative inspiration rather than definitive solutions. Important business decisions, legal documents, or professional communications should be reviewed by appropriate experts before implementation or distribution.
          </p>

          <h2 className="text-2xl font-semibold mt-8 mb-4">No Professional Advice</h2>
          <p>
            The information and outputs provided by Zyfoox do not constitute professional advice in any field, including but not limited to legal, financial, educational, marketing, or business advice. Our tools are designed to assist and provide general guidance but are not substitutes for professional consultation with qualified experts in relevant fields.
          </p>
          <p>
            For matters requiring specialized expertise, we strongly recommend consulting with appropriate professionals who can provide personalized advice tailored to your specific situation and needs.
          </p>

          <h2 className="text-2xl font-semibold mt-8 mb-4">External Links and Third-Party Content</h2>
          <p>
            Zyfoox may contain links to external websites or references to third-party content that are not owned or controlled by us. We have no control over and assume no responsibility for the content, privacy policies, or practices of any third-party websites or services. We do not warrant the offerings of any of these entities/individuals or their websites.
          </p>
          <p>
            You acknowledge and agree that Zyfoox shall not be responsible or liable, directly or indirectly, for any damage or loss caused or alleged to be caused by or in connection with the use of or reliance on any such content, goods, or services available on or through any such third-party websites or services.
          </p>

          <h2 className="text-2xl font-semibold mt-8 mb-4">Limitation of Liability</h2>
          <p>
            To the maximum extent permitted by applicable law, Zyfoox and its operators, directors, employees, agents, and affiliates shall not be liable for any indirect, punitive, incidental, special, consequential, or exemplary damages, including without limitation damages for loss of profits, goodwill, use, data, or other intangible losses, that result from:
          </p>
          
          <ul className="list-disc pl-6 space-y-2 mt-4">
            <li>The use of, or inability to use, the platform or any tools therein</li>
            <li>Any outputs, content, or suggestions generated by our AI tools</li>
            <li>The use of content downloaded through our tools</li>
            <li>Unauthorized access to or alteration of your transmissions or data</li>
            <li>Any other matter relating to the platform</li>
          </ul>
          
          <p>
            In no event shall our total liability to you for all damages, losses, or causes of action exceed the amount you have paid to Zyfoox in the past six months, or, if you have not paid Zyfoox for the use of any services, the amount of $100.00.
          </p>

          <h2 className="text-2xl font-semibold mt-8 mb-4">Changes to This Disclaimer</h2>
          <p>
            We reserve the right to modify this disclaimer at any time. Changes and clarifications will take effect immediately upon their posting on the website. We encourage users to check this page periodically for any changes. Your continued use of the platform following the posting of revised terms constitutes your acceptance of such changes.
          </p>

          <h2 className="text-2xl font-semibold mt-8 mb-4">Contact Us</h2>
          <p>
            If you have any questions about this disclaimer, please contact us through our <Link to="/contact" className="text-primary hover:underline">contact page</Link>.
          </p>

          <Separator className="my-8" />

          <p className="text-center text-muted-foreground">
            By using Zyfoox, you acknowledge that you have read, understood, and agree to be bound by this disclaimer.
          </p>
        </div>
      </div>
    </>
  );
}
